version: '3.3'

services:
    hw5-2:
        container_name: hw5-2
        build: .
        volumes:
            - ./:/app
        restart: always
        working_dir: /app
        command: bash -c "composer update && php server.php"
