version: '3.3'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    links:
      - php
    restart: always
    volumes:
      - ./app:/app
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
  php:
    build: ./php
    container_name: php-fpm
    volumes:
      - ./app:/app
