version: '3'

services:
    nginx:        
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www
            - ./hosts:/etc/nginx/conf.d
        links:
            - php
    php:
        build: ./images/php
        volumes:
            - ./www:/var/www
        links:
            - mysql
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}        

