version: "3"
networks:
  otus:
services:
  nginx:
    build: docker/nginx/
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - otus
  app:
    build: docker/php/
    working_dir: /var/www/
    volumes:
      - ./src/:/var/www
    networks:
      - otus
