version: '3'
services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        volumes:
            - ./src:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        links:
            - php
        
    php:
        image: php:7.2-fpm-alpine
        container_name: php
        volumes:
            - ./src:/var/www/html